# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  catalogdb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - catalog_data:/data/db

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - MongoDbSetting:ConnectionString=mongodb://catalogdb:27017
    depends_on:
      - catalogdb

  cartdb:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - cart_data:/data

  cartapi:
    image: cartapi
    build:
      context: .
      dockerfile: Services/Cart/Cart.Api/Dockerfile
    ports:
      - 5001:80
    environment:
      - RedisSetting:ConnectionString=cartdb:6379
    depends_on:
      - cartdb

volumes:
  catalog_data:
  cart_data:
