# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

  catalogdb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - catalog_data:/data/db
    restart: always

  cartdb:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - cart_data:/data
    restart: always

  discountdb:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - discount_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin$56789
      - POSTGRES_DB=discountdb
    restart: always

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - MongoDbSetting:ConnectionString=mongodb://catalogdb:27017
    depends_on:
      - catalogdb

  cartapi:
    image: cartapi
    build:
      context: .
      dockerfile: Services/Cart/Cart.Api/Dockerfile
    ports:
      - 5001:80
    environment:
      - RedisSetting:ConnectionString=cartdb:6379
    depends_on:
      - cartdb

volumes:
  portainer_data:
  catalog_data:
  cart_data:
  discount_data:
